[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Atliac"]
description = "Snapshot testing and assertion library for Rust"
repository = "https://github.com/atliac/assert-snap"
documentation = "https://docs.rs/assert-snap"
homepage = "https://github.com/atliac/assert-snap"
readme = "README.md"
keywords = ["snapshot", "testing", "assert", "snap"]
categories = ["development-tools::testing"]

[workspace]
resolver = "3"
members = ["assert-snap"]

[workspace.dependencies]
